### ISSUE TITLE
仅支持一个表，多个表启动报错

### ISSUE THREAD

**Issue by qyjhari** [marioplus/jpa-gen-demo#1]
生成多个表的代码没有问题，但是启动报错，报springbean注入冲突了
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-23 14:53:17.693 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'complaintService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.data.jpa.repository.JpaRepository<?, ?>' available: expected single matching bean but found 8: verPageRepository,verProductRepository,retMainRepository,verNodeRepository,verVersionRepository,complaintRepository,retTrackRepository,retVideoRepository
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:337)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.sinosoft.WebApplication.main(WebApplication.java:14)
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.data.jpa.repository.JpaRepository<?, ?>' available: expected single matching bean but found 8: verPageRepository,verProductRepository,retMainRepository,verNodeRepository,verVersionRepository,complaintRepository,retTrackRepository,retVideoRepository
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1265)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:537)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:513)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:653)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:224)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:334)
	... 17 common frames omitted

**Comment by marioplus** [comment]
作为本人人生中的第一个 `issues` 就多说几句吧
```
No qualifying bean of type 'org.springframework.data.jpa.repository.JpaRepository' available: expected single matching bean but found 8: verPageRepository,verProductRepository,retMainRepository,verNodeRepository,verVersionRepository,complaintRepository,retTrackRepository,retVideoRepository
```
如果你好好琢磨这个异常提示就知道哪里出了问题，类型为`org.springframework.data.jpa.repository.JpaRepository`的bean有8个，所以使用`org.springframework.data.jpa.repository.JpaRepository`来接受其实现会出错，应该使用下面的方式接受
```
@Resource
verPageRepository p1;
@Resource
verProductRepositoryp2;
...
```

**Comment by marioplus** [comment]
实例代码中已经包含了多个表
